---
scenario:
  name: nikola-el8
platforms:
  - name: ansible-test-builder
    # LXD
    source:
      alias: 'centos/8/amd64'
    # Docker
    image: 'centos:8'
  # this one is always the same
  - name: ansible-test-web
    # LXD
    source:
      alias: 'centos/8/amd64'
    # Docker
    image: 'centos:8'
provisioner:
  inventory:
    group_vars:
      all:
        # workaround for https://github.com/ansible/ansible/issues/70168
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      ansible-test-builder:
        builder: nikola
        # known working website
        git_url: https://pagure.io/koji-site.git
