---
scenario:
  name: ascii_binder_f30
platforms:
  - name: ansible-test-builder
    # LXD
    source:
      alias: 'fedora/30/amd64'
    # Docker
    image: 'fedora:30'
  # this one is always the same
  - name: ansible-test-web
    # LXD
    source:
      alias: 'centos/7/amd64'
    # Docker
    image: 'centos:7'
provisioner:
  inventory:
    host_vars:
      ansible-test-builder:
        ansible_python_interpreter: /usr/bin/python3
        builder: ascii_binder
        # known working website
        git_url: https://github.com/redhataccess/ascii_binder-docs.git
