---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not (lookup('env', 'MOLECULE_DEBUG') | bool or molecule_yml.provisioner.log|default(false) | bool) }}"
  tasks:
    - name: Apply global default parameters
      set_fact:
        final_platforms: "{{ final_platforms | default([]) | union([hostvars[item.name].platform_base.lxd|combine(item)]) }}"
      loop: "{{ molecule_yml.platforms }}"

    - name: Destroy molecule instance(s)
      lxd_container:
        url: "{{ item.url | default(omit) }}"
        cert_file: "{{ item.cert_file | default(omit) }}"
        key_file: "{{ item.key_file | default(omit) }}"
        trust_password: "{{ item.trust_password | default(omit) }}"
        name: "{{ item.name }}"
        state: absent
        force_stop: "{{ item.force_stop | default(true) }}"
      with_items: "{{ final_platforms }}"
