---

- name: Prepare builder host
  hosts: ansible-test-builder
  tasks:
    - name: Install builder tools
      package:
        name:
          - sudo              # needed for tests
          - openssh-clients   # to communicate between machines
          - crontabs          # to setup cron jobs
    - name: "Ensure locales variables are preserved with sudo"
      lineinfile:
        path: /etc/sudoers
        line: 'Defaults   env_keep += "LANG LANGUAGE LC_ALL"'
        state: present
        validate: /usr/sbin/visudo -cf %s
    # do not interfer with manual tests
    - name: Stop cron
      service:
        name: crond
        enabled: no
        state: stopped

- name: Prepare web host
  hosts: ansible-test-web
  tasks:
    - name: Install builder tools
      package:
        name:
          - openssh-server    # to communicate between machines
    - name: start SSH daemon
      service:
        name: sshd
        enabled: yes
        state: started
    - name: Open the firewall for {{ ssh_port }} using firewalld
      firewalld:
        port: "22/tcp"
        permanent: true
        state: enabled
        immediate: yes
      when: manage_firewall|default(True) and ansible_os_family == "RedHat"
    - name: create web builder's user
      user:
        name: web_builder
        comment: "Web Builder User"
    - name: create web directory
      file:
        path: /var/www/www.example.com
        state: directory
        owner: web_builder
        group: web_builder
        mode: 0775

