---
scenario:
  name: middleman-el7
platforms:
  - name: ansible-test-builder
    # LXD
    source:
      alias: 'centos/7/amd64'
    # Docker
    image: 'centos:7'
  # this one is always the same
  - name: ansible-test-web
    # LXD
    source:
      alias: 'centos/7/amd64'
    # Docker
    image: 'centos:7'
provisioner:
  inventory:
    group_vars:
      all:
        # workaround for https://github.com/ansible/ansible/issues/70168
        ansible_python_interpreter: /usr/bin/python
    host_vars:
      ansible-test-builder:
        builder: middleman
        # known working website
        git_url: https://gitlab.com/osas/middleman-springboard.git
