---
scenario:
  name: middleman-el7
platforms:
  - name: ansible-test-builder
    lxd:
      image: 'centos/7/amd64'
    docker:
      image: 'centos:7'
  # this one is always the same
  - name: ansible-test-web
    lxd:
      image: 'centos/7/amd64'
    docker:
      image: 'centos:7'
provisioner:
  inventory:
    host_vars:
      ansible-test-builder:
        builder: middleman
        # known working website
        git_url: https://gitlab.com/osas/middleman-springboard.git
