---
scenario:
  name: ascii_binder_f27
platforms:
  - name: ansible-test-builder
    lxd:
      image: 'fedora/27/amd64'
    docker:
      image: 'fedora:27'
  # this one is always the same
  - name: ansible-test-web
    lxd:
      image: 'centos/7/amd64'
    docker:
      image: 'centos:7'
provisioner:
  inventory:
    host_vars:
      ansible-test-builder:
        ansible_python_interpreter: /usr/bin/python3
        builder: ascii_binder
        # known working website
        git_url: https://github.com/redhataccess/ascii_binder-docs.git
