---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint --nocolor
  flake8
provisioner:
  name: ansible
  options:
    vv: True
  config_options:
    defaults:
      hash_behaviour: merge
  env:
    LANG: en_US.UTF-8
  playbooks:
    docker:
      create: ../_resources/create-docker.yml
      destroy: ../_resources/destroy-docker.yml
    lxd:
      create: ../_resources/create-lxd.yml
      destroy: ../_resources/destroy-lxd.yml
    prepare: ../_resources/prepare.yml
    converge: ../_resources/converge.yml
verifier:
  name: testinfra
  options:
    v: True
  lint:
    name: flake8
