---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
provisioner:
  name: ansible
  options:
    vv: True
  inventory:
    group_vars:
      all:
        platform_base:
          lxd:
            source:
              type: image
              server: https://images.linuxcontainers.org
          docker:
            hostname: "{{ item.name }}.example.com"
            command: /sbin/init
            privileged: True
            network_mode: bridge
            networks:
              - name: testnetwork
                aliases:
                  # allow access via short DNS name
                  - "{{ item.name }}"
    host_vars:
      ansible-test-builder:
      ansible-test-web:
  env:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
  playbooks:
    docker:
      create: ../_resources/create-docker.yml
      destroy: ../_resources/destroy-docker.yml
    lxd:
      create: ../_resources/create-lxd.yml
      destroy: ../_resources/destroy-lxd.yml
    prepare: ../_resources/prepare.yml
    converge: ../_resources/playbook.yml
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
