---
scenario:
  name: planet-el7
platforms:
  - name: ansible-test-builder
    lxd:
      image: 'centos/7/amd64'
    docker:
      image: 'centos:7'
  # this one is always the same
  - name: ansible-test-web
    lxd:
      image: 'centos/7/amd64'
    docker:
      image: 'centos:7'
provisioner:
  inventory:
    host_vars:
      ansible-test-builder:
        builder: planet
        # known working website
        git_url: https://github.com/redhat-openstack/website.git
