---
scenario:
  name: planet-el7
platforms:
  - name: ansible-test-builder
    # LXD
    source:
      alias: 'centos/7/amd64'
    # Docker
    image: 'centos:7'
  # this one is always the same
  - name: ansible-test-web
    # LXD
    source:
      alias: 'centos/7/amd64'
    # Docker
    image: 'centos:7'
provisioner:
  inventory:
    host_vars:
      ansible-test-builder:
        builder: planet
        # known working website
        git_url: https://gitlab.com/osas/ansible-role-web_builder_test_planet.git
